apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: attacker-egress-only
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: attacker
  policyTypes:
    - Egress
    - Ingress
  egress:
    - {}   # Allow all outgoing connections
  ingress: []
