services:
  target:
    build: ./target
    container_name: target
    networks:
      production-net:
        ipv4_address: 172.30.0.3
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default &&
             ip route add default via 172.30.0.5 &&
             service ssh start &&
             service nginx start &&
             sleep infinity"

  suricata:
    build: ./suricata
    container_name: suricata
    networks:
      sensor-net:
        ipv4_address: 172.29.0.2
    volumes:
      - ../suricata/logs:/var/log/suricata
    cap_add:
      - NET_ADMIN
    command: sh -c "suricata-update && suricata -i eth0 -c /etc/suricata/suricata.yaml -v"
    
  adversary:
    build: ./adversary
    container_name: adversary
    networks:
      external-net:
        ipv4_address: 172.28.0.4
    cap_add:
      - NET_ADMIN
    command: >
        sh -c "ip route add 172.30.0.0/24 via 172.28.0.5 dev eth0 &&
             sleep infinity"
  
  gateway:
    build: ./gateway
    container_name: gateway
    privileged: true
    networks:
      external-net:
        ipv4_address: 172.28.0.5
      sensor-net:
        ipv4_address: 172.29.0.5
      production-net:
        ipv4_address: 172.30.0.5
    command: >
      sh -c "sysctl -w net.ipv4.ip_forward=1 &&
            /tmp/tc_init.sh &&
            sleep infinity"

networks:
  external-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
  sensor-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
  production-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
