services:

  target:
    build: ./target
    container_name: target
    networks:
      internal-net:
        ipv4_address: 172.30.0.3
    cap_add:
      - NET_ADMIN
    command: sh /scripts/init.sh

  suricata:
    build: ./suricata
    container_name: suricata
    networks:
      ids-central-net:
        ipv4_address: 172.29.0.2
    volumes:
      - ../suricata/logs:/var/log/suricata
    cap_add:
      - NET_ADMIN
    command: sh /scripts/init.sh
    
  adversary:
    build: ./adversary
    container_name: adversary
    networks:
      external-net:
        ipv4_address: 172.28.0.4
    cap_add:
      - NET_ADMIN
    command: sh /scripts/init.sh
  
  gateway:
    build: ./gateway
    container_name: gateway
    privileged: true
    networks:
      external-net:
        ipv4_address: 172.28.0.5
      ids-central-net:
        ipv4_address: 172.29.0.5
      internal-net:
        ipv4_address: 172.30.0.5
      monitoring-net:
        ipv4_address: 172.31.0.5
    command: sh /scripts/init.sh
  
  dns:
    build: ./dns
    container_name: dns
    networks:
      external-net:
        ipv4_address: 172.28.0.53
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ./dns/config/dnsmasq.conf:/etc/dnsmasq.d/00-lab.conf
      - ./dns/config/hosts.txt:/etc/dnsmasq.hosts
    cap_add:
      - NET_ADMIN

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      monitoring-net:
        ipv4_address: 172.31.0.2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      monitoring-net:
        ipv4_address: 172.31.0.3
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    networks:
      monitoring-net:
        ipv4_address: 172.31.0.4
    volumes:
      - ../suricata/logs:/var/log/suricata
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      monitoring-net:
        ipv4_address: 172.31.0.6
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  external-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
  ids-central-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
  monitoring-net:
      driver: bridge
      ipam:
        config:
          - subnet: 172.31.0.0/24