services:

  target:
    build: ./target
    container_name: target
    networks:
      internal-net:
        ipv4_address: 172.30.0.3
    cap_add:
      - NET_ADMIN
    command: sh /scripts/init.sh

  suricata:
    build: ./suricata
    container_name: suricata
    networks:
      sensor-net:
        ipv4_address: 172.29.0.2
    volumes:
      - ../suricata/logs:/var/log/suricata
    cap_add:
      - NET_ADMIN
    command: sh /scripts/init.sh
    
  adversary:
    build: ./adversary
    container_name: adversary
    networks:
      external-net:
        ipv4_address: 172.28.0.4
    cap_add:
      - NET_ADMIN
    command: sh /scripts/init.sh
  
  gateway:
    build: ./gateway
    container_name: gateway
    privileged: true
    networks:
      external-net:
        ipv4_address: 172.28.0.5
      sensor-net:
        ipv4_address: 172.29.0.5
      internal-net:
        ipv4_address: 172.30.0.5
    command: sh /scripts/init.sh
  
  dns:
    build: ./dns
    container_name: dns
    networks:
      external-net:
        ipv4_address: 172.28.0.53
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ./dns/config/dnsmasq.conf:/etc/dnsmasq.d/00-lab.conf
      - ./dns/config/hosts.txt:/etc/dnsmasq.hosts
    cap_add:
      - NET_ADMIN

networks:
  external-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
  sensor-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
